export interface Language {
  code: string
  name: string
  nativeName: string
  translations: {
    like: string
    reply: string
    message: string
    min: string
    hour: string
    day: string
    week: string
    month: string
    year: string
  }
}

export const languages: Language[] = [
  {
    code: "BG",
    name: "Bulgarian",
    nativeName: "Български",
    translations: {
      like: "Харесва ми",
      reply: "Отговор",
      message: "Съобщение",
      min: "мин",
      hour: "ч",
      day: "дни",
      week: "седмици",
      month: "месец",
      year: "година",
    },
  },
  {
    code: "RU",
    name: "Russian",
    nativeName: "Русский",
    translations: {
      like: "Нравится",
      reply: "Ответить",
      message: "Сообщение",
      min: "мин",
      hour: "ч",
      day: "дн",
      week: "нед",
      month: "мес",
      year: "год",
    },
  },
  {
    code: "EN",
    name: "English",
    nativeName: "English",
    translations: {
      like: "Like",
      reply: "Reply",
      message: "Message",
      min: "min",
      hour: "h",
      day: "d",
      week: "w",
      month: "mo",
      year: "y",
    },
  },
  {
    code: "ES",
    name: "Spanish",
    nativeName: "Español",
    translations: {
      like: "Me gusta",
      reply: "Responder",
      message: "Mensaje",
      min: "min",
      hour: "h",
      day: "d",
      week: "sem",
      month: "mes",
      year: "año",
    },
  },
  {
    code: "FR",
    name: "French",
    nativeName: "Français",
    translations: {
      like: "J'aime",
      reply: "Répondre",
      message: "Message",
      min: "min",
      hour: "h",
      day: "j",
      week: "sem",
      month: "mois",
      year: "an",
    },
  },
  {
    code: "DE",
    name: "German",
    nativeName: "Deutsch",
    translations: {
      like: "Gefällt mir",
      reply: "Antworten",
      message: "Nachricht",
      min: "Min",
      hour: "Std",
      day: "T",
      week: "W",
      month: "Mon",
      year: "J",
    },
  },
  {
    code: "IT",
    name: "Italian",
    nativeName: "Italiano",
    translations: {
      like: "Mi piace",
      reply: "Rispondi",
      message: "Messaggio",
      min: "min",
      hour: "h",
      day: "g",
      week: "sett",
      month: "mese",
      year: "anno",
    },
  },
  {
    code: "PT",
    name: "Portuguese",
    nativeName: "Português",
    translations: {
      like: "Curtir",
      reply: "Responder",
      message: "Mensagem",
      min: "min",
      hour: "h",
      day: "d",
      week: "sem",
      month: "mês",
      year: "ano",
    },
  },
  {
    code: "PL",
    name: "Polish",
    nativeName: "Polski",
    translations: {
      like: "Lubię to",
      reply: "Odpowiedz",
      message: "Wiadomość",
      min: "min",
      hour: "godz",
      day: "dni",
      week: "tyg",
      month: "mies",
      year: "rok",
    },
  },
  {
    code: "UK",
    name: "Ukrainian",
    nativeName: "Українська",
    translations: {
      like: "Подобається",
      reply: "Відповісти",
      message: "Повідомлення",
      min: "хв",
      hour: "год",
      day: "дн",
      week: "тиж",
      month: "міс",
      year: "рік",
    },
  },
  {
    code: "TR",
    name: "Turkish",
    nativeName: "Türkçe",
    translations: {
      like: "Beğen",
      reply: "Yanıtla",
      message: "Mesaj",
      min: "dk",
      hour: "sa",
      day: "g",
      week: "hf",
      month: "ay",
      year: "yıl",
    },
  },
  {
    code: "AR",
    name: "Arabic",
    nativeName: "العربية",
    translations: {
      like: "أعجبني",
      reply: "رد",
      message: "رسالة",
      min: "د",
      hour: "س",
      day: "ي",
      week: "أ",
      month: "ش",
      year: "س",
    },
  },
  {
    code: "JA",
    name: "Japanese",
    nativeName: "日本語",
    translations: {
      like: "いいね！",
      reply: "返信する",
      message: "メッセージ",
      min: "分",
      hour: "時間",
      day: "日",
      week: "週",
      month: "ヶ月",
      year: "年",
    },
  },
  {
    code: "KO",
    name: "Korean",
    nativeName: "한국어",
    translations: {
      like: "좋아요",
      reply: "답글 달기",
      message: "메시지",
      min: "분",
      hour: "시간",
      day: "일",
      week: "주",
      month: "개월",
      year: "년",
    },
  },
  {
    code: "ZH",
    name: "Chinese",
    nativeName: "中文",
    translations: {
      like: "赞",
      reply: "回复",
      message: "发消息",
      min: "分钟",
      hour: "小时",
      day: "天",
      week: "周",
      month: "月",
      year: "年",
    },
  },
  {
    code: "HI",
    name: "Hindi",
    nativeName: "हिन्दी",
    translations: {
      like: "पसंद",
      reply: "जवाब दें",
      message: "संदेश",
      min: "मिनट",
      hour: "घंटा",
      day: "दिन",
      week: "सप्ताह",
      month: "महीना",
      year: "साल",
    },
  },
  {
    code: "NL",
    name: "Dutch",
    nativeName: "Nederlands",
    translations: {
      like: "Vind ik leuk",
      reply: "Reageren",
      message: "Bericht",
      min: "min",
      hour: "u",
      day: "d",
      week: "w",
      month: "mnd",
      year: "j",
    },
  },
  {
    code: "SV",
    name: "Swedish",
    nativeName: "Svenska",
    translations: {
      like: "Gilla",
      reply: "Svara",
      message: "Meddelande",
      min: "min",
      hour: "tim",
      day: "d",
      week: "v",
      month: "mån",
      year: "år",
    },
  },
  {
    code: "CS",
    name: "Czech",
    nativeName: "Čeština",
    translations: {
      like: "To se mi líbí",
      reply: "Odpovědět",
      message: "Zpráva",
      min: "min",
      hour: "hod",
      day: "d",
      week: "týd",
      month: "měs",
      year: "rok",
    },
  },
  {
    code: "RO",
    name: "Romanian",
    nativeName: "Română",
    translations: {
      like: "Îmi place",
      reply: "Răspunde",
      message: "Mesaj",
      min: "min",
      hour: "oră",
      day: "zi",
      week: "săpt",
      month: "lună",
      year: "an",
    },
  },
  {
    code: "EL",
    name: "Greek",
    nativeName: "Ελληνικά",
    translations: {
      like: "Μου αρέσει",
      reply: "Απάντηση",
      message: "Μήνυμα",
      min: "λεπτά",
      hour: "ώρα",
      day: "ημέρα",
      week: "εβδομάδα",
      month: "μήνας",
      year: "έτος",
    },
  },
  {
    code: "HU",
    name: "Hungarian",
    nativeName: "Magyar",
    translations: {
      like: "Tetszik",
      reply: "Válasz",
      message: "Üzenet",
      min: "perc",
      hour: "óra",
      day: "nap",
      week: "hét",
      month: "hónap",
      year: "év",
    },
  },
  {
    code: "TH",
    name: "Thai",
    nativeName: "ไทย",
    translations: {
      like: "ถูกใจ",
      reply: "ตอบกลับ",
      message: "ข้อความ",
      min: "นาที",
      hour: "ชั่วโมง",
      day: "วัน",
      week: "สัปดาห์",
      month: "เดือน",
      year: "ปี",
    },
  },
  {
    code: "VI",
    name: "Vietnamese",
    nativeName: "Tiếng Việt",
    translations: {
      like: "Thích",
      reply: "Trả lời",
      message: "Nhắn tin",
      min: "phút",
      hour: "giờ",
      day: "ngày",
      week: "tuần",
      month: "tháng",
      year: "năm",
    },
  },
  {
    code: "ID",
    name: "Indonesian",
    nativeName: "Bahasa Indonesia",
    translations: {
      like: "Suka",
      reply: "Balas",
      message: "Pesan",
      min: "mnt",
      hour: "jam",
      day: "hari",
      week: "minggu",
      month: "bulan",
      year: "tahun",
    },
  },
  {
    code: "HE",
    name: "Hebrew",
    nativeName: "עברית",
    translations: {
      like: "אהבתי",
      reply: "הגב",
      message: "הודעה",
      min: "דק׳",
      hour: "שעה",
      day: "יום",
      week: "שבוע",
      month: "חודש",
      year: "שנה",
    },
  },
  {
    code: "SR",
    name: "Serbian",
    nativeName: "Српски",
    translations: {
      like: "Свиђа ми се",
      reply: "Одговори",
      message: "Порука",
      min: "мин",
      hour: "сат",
      day: "дан",
      week: "недеља",
      month: "месец",
      year: "година",
    },
  },
  {
    code: "HR",
    name: "Croatian",
    nativeName: "Hrvatski",
    translations: {
      like: "Sviđa mi se",
      reply: "Odgovori",
      message: "Poruka",
      min: "min",
      hour: "sat",
      day: "dan",
      week: "tjedan",
      month: "mjesec",
      year: "godina",
    },
  },
  {
    code: "SK",
    name: "Slovak",
    nativeName: "Slovenčina",
    translations: {
      like: "Páči sa mi to",
      reply: "Odpovedať",
      message: "Správa",
      min: "min",
      hour: "hod",
      day: "deň",
      week: "týždeň",
      month: "mesiac",
      year: "rok",
    },
  },
  {
    code: "FI",
    name: "Finnish",
    nativeName: "Suomi",
    translations: {
      like: "Tykkää",
      reply: "Vastaa",
      message: "Viesti",
      min: "min",
      hour: "t",
      day: "pv",
      week: "vk",
      month: "kk",
      year: "v",
    },
  },
  {
    code: "NO",
    name: "Norwegian",
    nativeName: "Norsk",
    translations: {
      like: "Lik",
      reply: "Svar",
      message: "Melding",
      min: "min",
      hour: "t",
      day: "d",
      week: "u",
      month: "mnd",
      year: "år",
    },
  },
  {
    code: "DA",
    name: "Danish",
    nativeName: "Dansk",
    translations: {
      like: "Synes godt om",
      reply: "Svar",
      message: "Besked",
      min: "min",
      hour: "t",
      day: "d",
      week: "u",
      month: "md",
      year: "år",
    },
  },
]
